name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Enter URL '...'
        3. Select theme '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.

  - type: dropdown
    id: theme
    attributes:
      label: Theme Used
      description: Which theme were you using?
      options:
        - minimal (default)
        - mono
        - neon
        - pastel
        - sunset
        - midnight
        - glass
        - retro
        - N/A

  - type: dropdown
    id: layout
    attributes:
      label: Layout Used
      description: Which layout were you using?
      options:
        - regular (default)
        - compact
        - wide
        - N/A

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (browser, OS, etc.).
