name: Theme / Template Request
description: Request a new theme or card template
labels: ["enhancement", "theme"]
body:
  - type: markdown
    attributes:
      value: |
        Want a new theme or card template? Describe your idea below!

  - type: input
    id: name
    attributes:
      label: Theme / Template Name
      description: A short name for the proposed theme or template.
      placeholder: e.g. "cyberpunk", "ocean", "nordic"
    validations:
      required: true

  - type: textarea
    id: style
    attributes:
      label: Style Description
      description: Describe the visual style, mood, and colors you have in mind.
      placeholder: |
        - Primary colors: ...
        - Mood/vibe: ...
        - Background style: ...
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: Reference Images / Colors
      description: |
        Share any reference images, color palettes, or links that capture the style.
        You can paste image URLs or drag & drop screenshots.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details about the theme/template request.
